templates/prelogin/base.html, urls.py, views.py
@orangejenny teeny details before release
=> Update final things

templates/prelogin/_sections/services_details/bundles.html
http://manage.dimagi.com/default.asp?167863
@biyeun
=> open contact form on button click

templates/prelogin/_sections/solutions/supply_intro.html
http://manage.dimagi.com/default.asp?167849
@sravfeyn
=> add supply anchor

templates/prelogin/base.html, templates/prelogin/home.html
Add KISSmetrics page view tracking to all pre-login pages and add event for clicking sign up.
FYI @czue
=> Add kissmetrics tracking

templates/prelogin/home.html
Executes the callback after a short timeout if KISSmetrics doesn't execute it first.
http://manage.dimagi.com/default.asp?171220#959050
=> Don't block form submission if KISSmetrics isn't working

templates/prelogin/home.html
Depends on https://github.com/dimagi/commcare-hq/pull/7101, so hold off on merge until that's ready.
cc @nickpell, @sravfeyn
=> Use new KISSmetrics helper function

templates/prelogin/_sections/services_details/bundles.html
@emord cody buddy. quick one for you
=> remove duplicate line

templates/prelogin/_sections/pricing/lead.html
http://manage.dimagi.com/default.asp?174084
buddy @dannyroberts ping @snopoke
=> Added missing link to FAQs

templates/prelogin/_sections/pricing/lead.html
http://manage.dimagi.com/default.asp?174353#966862
cc: @biyeun
=> Fix pricing link

templates/prelogin/_sections/pricing/analytics.html
http://manage.dimagi.com/default.asp?171035#966889
cc: @biyeun
=> Remove info bubble

forms.py, static/prelogin/less/includes/mixins.less, static/prelogin/less/includes/variables.less, templates/prelogin/base.html, views.py
updating imports for crispy forms, making sure that bootstrap3 is enabled
=> B3 migration prep

forms.py
I tested this one out locally, should be g2m without QA
@biyeun @sravfeyn
=> Switch from ugettext_noop to ugettext_lazy

templates/prelogin/base.html
http://manage.dimagi.com/default.asp?176390
@biyeun
=> Separate SITE_NAME and title with a " - "

static/prelogin/less/components/form.less
@nickpell 
for issues with compress
=> fix relative path in forms

tests/__init__.py, tests/test_views.py
=> Sanity checking for prelogin

templates/prelogin/base.html
=> switch to angularjs 1.4.4

templates/prelogin/_sections/pricing/05_data_security.html, templates/prelogin/_sections/pricing/06_user_management.html, templates/prelogin/_sections/pricing/07_system_integration.html
[FB 179631](http://manage.dimagi.com/default.asp?179631)
@snopoke, cc @biyeun, @emord, @gcapalbo
=> Reconcile pricing plan with permissions

static/prelogin/less/includes/mixins.less, static/prelogin/less/includes/variables.less, static/prelogin/less/public-style-imports.less, static/prelogin/less/public-style.debug.less, static/prelogin/less/public-style.less, static/prelogin/less/settings.realtime.less, templates/prelogin/base.html
=> Fix prelogin lessjs

templates/prelogin/base.html
http://manage.dimagi.com/default.asp?180234#1003302
(ticket says fee free, but I changed it to feel)
cc: @czue
=> Add text to contact us

urls.py
http://manage.dimagi.com/default.asp?180289
=> first-class supply URL

static/prelogin/less/components/pricing-section.less, static/prelogin/less/components/pricing.less, templates/prelogin/_sections/pricing/02_app_features.html, templates/prelogin/_sections/pricing/03_messaging_sms.html, templates/prelogin/_sections/pricing/04_reporting_analytics.html, templates/prelogin/_sections/pricing/06_user_management.html, templates/prelogin/_sections/pricing/07_system_integration.html
=> Misc pricing page changes

templates/prelogin/_sections/pricing/04_reporting_analytics.html
codebuddy @gcapalbo 
http://manage.dimagi.com/default.asp?182314#1017227
=> data management is standard

templates/prelogin/base.html
@proteusvacuum @sravfeyn depends on https://github.com/dimagi/commcare-hq/pull/8476
=> Kill underscore

templates/prelogin/base.html
=> kill angular

views.py
=> cleanup syntax for use_bootstrap3 decorator

templates/prelogin/base.html
@TylerSheffels http://manage.dimagi.com/default.asp?184002
=> Use other GA account

templates/prelogin/_sections/pricing/03_messaging_sms.html
http://manage.dimagi.com/default.asp?186979#1044834
@gcapalbo
=> update messaging pricing page

templates/prelogin/base.html
@snopoke I am 95% sure this is the correct name based on your commits, but can you confirm.
cc: @dannyroberts 
http://manage.dimagi.com/default.asp?181375
=> Rename the google analytics ID to match the renaming that occurred in HQ

static/prelogin/less/components/pricing-section.less, templates/prelogin/_sections/pricing/03_messaging_sms.html
@biyeun is there a better way to figure out how many more pixels the whole section should be then doing it by feel?
cc: @dannyroberts 
http://manage.dimagi.com/default.asp?187012
=> Fix pricing table spacing

templates/prelogin/_sections/pricing/01_app_mangement.html, templates/prelogin/_sections/pricing/02_app_features.html
http://manage.dimagi.com/default.asp?188406
diff is better commit-by-commit
@dannyroberts / @proteusvacuum
=> Pricing tweaks

static/prelogin/less/components/pricing-section.less, static/prelogin/less/components/pricing.less, templates/prelogin/_sections/pricing/03_messaging_sms.html, templates/prelogin/_sections/pricing/fine_print.html, templates/prelogin/_sections/software_services/pricing.html
http://manage.dimagi.com/default.asp?188584
@biyeun @sravfeyn
=> Misc SMS pricing copy updates

templates/prelogin/home.html
@biyeun this fails when using the other compressor (uglifier). this should be in js-inline anyways
=> Move script to js-inline

templates/prelogin/base.html
with this, https://github.com/dimagi/commcarehq-prelogin/blob/master/templates/prelogin/home.html#L5-L18 is never included
cc: @esoergel
=> Include kissmetrics js-inline

static/prelogin/less/components/pricing-section.less, static/prelogin/less/components/pricing.less, templates/prelogin/_sections/pricing/02_app_features.html, templates/prelogin/_sections/pricing/06_user_management.html
@nickpell @emord (anyone on interrupt)
=> cleanup pricing table styling

templates/prelogin/_sections/home/build.html, templates/prelogin/_sections/software_services/bundles.html, templates/prelogin/_sections/software_services/capacity.html, templates/prelogin/_sections/software_services/pricing.html, templates/prelogin/base.html, tests/test_views.py, urls.py, views.py
Implements https://docs.google.com/document/d/1UGY1BZImTLy4RuGmdo5I0I03T09AnUURq6tju_Kc-Xc/edit#heading=h.k510mzz98ab7
=> Options to see prelogin site in multiple languages

templates/prelogin/_sections/pricing/04_reporting_analytics.html
@dimagi/product @benrudolph @kaapstorm @millerdev 
http://manage.dimagi.com/default.asp?190937#1071108
=> removing report builder from pricing page

views.py
=> explicitly specify use of angular js

templates/prelogin/home.html
http://manage.dimagi.com/default.asp?215496
looks like this has been broken since https://github.com/dimagi/commcarehq-prelogin/pull/36
@calellowitz cc @proteusvacuum
=> fix email auto-entry on sign up

templates/prelogin/_sections/pricing/06_user_management.html
@benrudolph @biyeun cc: @dannyroberts
=> Role-based access is not allowed on community

templates/prelogin/_sections/software_services/bundles.html, templates/prelogin/_sections/software_services/capacity.html, templates/prelogin/_sections/software_services/pricing.html, templates/prelogin/base.html, views.py
Changes prefix url behaviour as per https://docs.google.com/document/d/1xckRTOH9TFbUGOClo3uT5PpIlt6T7Fh2bli6Mhu19xo/edit
@czue 
cc @orangejenny
=> change prefix URL behaviour

templates/prelogin/_sections/software_services/bundles.html, templates/prelogin/_sections/software_services/capacity.html, templates/prelogin/_sections/software_services/pricing.html
this should fix the build.
@sravfeyn fyi
=> add missing template_tags imports

static/prelogin/less/public-style.debug.less, static/prelogin/less/public-style.less, templates/prelogin/base.html
=> Fixes from bower move

templates/prelogin/_sections/impact/lead.html
@biyeun @emord 
http://manage.dimagi.com/default.asp?219662#1100219
Screenshot:
=> changing impact language

templates/prelogin/_sections/software_services/bundles.html, templates/prelogin/_sections/software_services/lead.html, templates/prelogin/_sections/software_services/pricing.html, urls.py, views.py
This PR builds on #64 to add a redirect, allow the old named anchors to still work, and resolve the language code 404ing.
Context [FB 219898](http://manage.dimagi.com/default.asp?219898) and [FB 220372](http://manage.dimagi.com/default.asp?220372).
@calellowitz @benrudolph cc @dannyroberts @biyeun
=> Pricing URLs

templates/prelogin/_sections/software_services/pricing.html
@benrudolph @kaapstorm cc: @NoahCarnahan @biyeun
http://manage.dimagi.com/default.asp?221120#1107280
=> removing report builder from pricing overview

templates/prelogin/_sections/pricing/01_app_mangement.html, templates/prelogin/_sections/pricing/02_app_features.html, templates/prelogin/_sections/pricing/03_messaging_sms.html, templates/prelogin/_sections/pricing/04_reporting_analytics.html, templates/prelogin/_sections/pricing/06_user_management.html, templates/prelogin/_sections/pricing/07_system_integration.html, templates/prelogin/_sections/pricing/08_support.html
@biyeun @orangejenny cc @calellowitz @millerdev
=> Dry up the pricing page

templates/prelogin/_sections/software_services/bundles.html, templates/prelogin/_sections/software_services/capacity.html, templates/prelogin/_sections/software_services/pricing.html, views.py
Interdependent with https://github.com/dimagi/commcare-hq/pull/11001
=> respond to TABS refactor

templates/prelogin/base.html
Missed committing this as part of https://github.com/dimagi/commcare-hq/pull/11055
@calellowitz
=> Fix base template title

templates/prelogin/home.html
@proteusvacuum this updates text and adds a CTA as specified in this ticket: http://manage.dimagi.com/default.asp?226668
cc: @millerdev
=> call to action button and text update

templates/prelogin/home.html
@millerdev as requested in the ticket: http://manage.dimagi.com/default.asp?226668
=> blue button to orange button

templates/prelogin/_sections/software_services/pricing.html
@gcapalbo 
http://manage.dimagi.com/default.asp?227098#1151704
=> fixing email support language

templates/prelogin/base.html
@emord @czue cc: @biyeun 
add fullstory tracking to prelogin site
=> adding fullstory to prelogin site

LICENSE.md, README.md
=> add license and update readme for devving on prelogin

static/prelogin/less/components/background.less, templates/prelogin/base.html, templates/prelogin/home.html, templates/prelogin/impact.html, templates/prelogin/pricing.html, templates/prelogin/services.html, templates/prelogin/software_services.html, templates/prelogin/solutions.html
Loads backgrounds on all pages asynchronously instead of synchronous with the rest of the page's images.
@orangejenny cc @calellowitz
=> Load backgrounds asynchronously

templates/prelogin/base.html
=> fix compress: remove compress js around blazy block

templates/prelogin/_sections/pricing/lead.html, templates/prelogin/_sections/software_services/pricing.html
http://manage.dimagi.com/default.asp?229302
@kaapstorm
=> Direct users to registration page

templates/prelogin/_sections/pricing/lead.html
Merge at same time as https://github.com/dimagi/commcare-hq/pull/12250
=> update community included users from 50 to 10

tests/__init__.py
=> Remove test imports for django test runner

templates/prelogin/_sections/pricing/04_reporting_analytics.html
http://manage.dimagi.com/default.asp?237972#1223035
=> moving excel dashboards to standard plan on the pricing page

templates/prelogin/home.html
=> changing demo link

templates/prelogin/base.html, templates/prelogin/demo.html
Wasn't using `kmqPushSafe` correctly. Replacing it with the more generic `analytics.workflow`.
@benrudolph / @calellowitz
=> Fix demo events

templates/prelogin/demo.html
=> rename template in prep for app manager v2

static/prelogin/less/components/pricing-section.less, templates/prelogin/_sections/pricing/06_user_management.html
=> Add organization-based access restrictions to pricing page

urls.py
remove ```RemovedInDjango19Warning: Default value of 'RedirectView.permanent' will change from True to False in Django 1.9. Set an explicit value to silence this warning.```
=> assign permanent explicitly

templates/prelogin/_sections/pricing/06_user_management.html
Reverts dimagi/commcarehq-prelogin#104
=> Revert "Update Restict Access by Location title"

templates/prelogin/_sections/pricing/06_user_management.html
Reverts dimagi/commcarehq-prelogin#105 @mkangia 
Goes with https://github.com/dimagi/commcare-hq/pull/13362
=> Revert "Revert "Update Restict Access by Location title""

templates/prelogin/base.html
=> Don't include fullstory if there is no FULLSTORY_ID set

static/prelogin/less/components/bundle.less, templates/prelogin/_sections/services/bundles.html, templates/prelogin/_sections/services/capacity.html, templates/prelogin/_sections/software_services/bundles.html, templates/prelogin/_sections/software_services/capacity.html
pricing page redesign as per https://docs.google.com/document/d/1CwXPl9Mfjpp_NHX7RJ2Wums4VHj7EkNAETh1esBxv5c/edit#
@biyeun
code buddies: @mkangia @nickpell 
cc @dimagi/product @gjavetski
=> pricing page redesign

templates/prelogin/_sections/software_services/bundles.html
@nickpell @mkangia 
spec was updated
=> fixing spec typo

templates/prelogin/base.html
Depends on https://github.com/dimagi/commcare-hq/pull/14426
@czue / @biyeun
=> Rename img to images in HQ

templates/prelogin/_sections/pricing/lead.html
=> new mobile worker pricing

urls.py, views.py
=> make imports safer

static/prelogin/js/drift.js, static/prelogin/js/hubspot_drift.js, templates/prelogin/home.html, templates/prelogin/pricing.html, templates/prelogin/software_services.html
=> Added Drift.com integration

tests/test_views.py
Fix tests for https://github.com/dimagi/commcare-hq/pull/15246 and https://github.com/dimagi/commcare-hq/pull/15248
@millerdev
=> Remove form builder demo test

templates/prelogin/base.html
@calellowitz can you merge this in quickly please? comms apparently needs this urgently
=> update cta to dimagi.com demo link

views.py
=> replace django.core.urlresolvers with django.urls

templates/prelogin/base.html
@biyeun 
This loads drift after fullstory so it can properly integrate
=> putting drift below fullstory

templates/prelogin/_sections/pricing/06_user_management.html
@dannyroberts // cc @orangejenny @kaapstorm
=> Make correction on pricing page

templates/prelogin/base.html
@orangejenny @biyeun cc: @millerdev 
tracking code for marketing
=> adding google tag manager

templates/prelogin/base.html
:wave: dimagi! 
been learning a bit about SEO and noticed we aren't doing a couple really simple things on HQ so decided to address that. 
I pulled the copy from https://www.dimagi.com/products/ assuming that was what we wanted to target
=> add more descriptive title and meta description tag

templates/prelogin/base.html
See https://github.com/dimagi/commcare-hq/pull/17264
@snopoke / @biyeun
=> Kill LESS_WATCH

static/prelogin/less/components/bundle.less, static/prelogin/less/components/pricing-row.less, static/prelogin/less/components/pricing-section.less, static/prelogin/less/components/pricing.less, static/prelogin/less/components/section.less, static/prelogin/less/public-style-imports.less, templates/prelogin/_sections/pricing/01_app_mangement.html, templates/prelogin/_sections/pricing/02_app_features.html, templates/prelogin/_sections/pricing/03_messaging_sms.html, templates/prelogin/_sections/pricing/04_reporting_analytics.html, templates/prelogin/_sections/pricing/05_data_security.html, templates/prelogin/_sections/pricing/06_user_management.html, templates/prelogin/_sections/pricing/07_system_integration.html, templates/prelogin/_sections/pricing/08_support.html, templates/prelogin/_sections/pricing/lead.html, templates/prelogin/_sections/services/bundles.html, templates/prelogin/_sections/software_services/shared_pricing_table.html, templates/prelogin/base.html
=> Improve multilingual formatting on pricing pages

static/prelogin/less/components/pricing-section.less, templates/prelogin/_sections/pricing/02_app_features.html
=> fix formatting issues in windows

templates/prelogin/base.html
Deploy same day as https://github.com/dimagi/commcare-hq/pull/17676
@gcapalbo / @calellowitz
=> Start merging style app into hqwebapp

templates/prelogin/base.html
Goes with https://github.com/dimagi/commcare-hq/pull/17682
@calellowitz / @gcapalbo
=> Start moving style templates to hqwebapp

views.py
@gcapalbo / @calellowitz 
goes with https://github.com/dimagi/commcare-hq/pull/17689
=> Move style decorators

static/prelogin/less/public-style.less, static/prelogin/less/settings.realtime.less, templates/prelogin/base.html
Goes with https://github.com/dimagi/commcare-hq/pull/17754
@gcapalbo / @dannyroberts
=> Move style/less

templates/prelogin/base.html
=> removing gtm

README.md, views.py
=> allowing caching of prelogin views & how to purge them

static/prelogin/less/public-style.less
@orangejenny  😳 
cc buddy @proteusvacuum
=> fix filter error

ab_tests.py, static/prelogin/less/components/section.less, templates/prelogin/_sections/home/lead.html, templates/prelogin/base.html, templates/prelogin/home.html, views.py
Here is the spec
https://docs.google.com/document/d/1WqOUlhazAnW3-OAlAY2F9v-S0bN0qaur18uvYJohfyo/edit
@dannyroberts 
cc @calellowitz
=> Add Prelogin Video Marketing A/B Test

ab_tests.py, templatetags/pricing_tags.py, tests/test_views.py
=> add 'from __future__ import absolute_import' to all .py files

static/prelogin/less/components/pricing-section.less, templates/prelogin/_sections/pricing/04_reporting_analytics.html
=> add report builder to pricing table

templates/prelogin/_sections/home/lead.html
@emord @orangejenny quick fix to get in for deploy
=> [ci skip] fix url for marketing video

templates/prelogin/base.html
Goes along with https://github.com/dimagi/commcare-hq/pull/18650
Needs to be merged before next deploy.
@nickpell / @calellowitz
=> Rename analytics modules to 'analytix'

templates/prelogin/base.html
Same idea as https://github.com/dimagi/commcarehq-prelogin/pull/147
@calellowitz / @nickpell
=> Rename kissmetrics module to kissmetrix

templatetags/pricing_tags.py
=> remove .keys()

templates/prelogin/base.html
=> correct var

templates/prelogin/base.html
Depends on https://github.com/dimagi/commcare-hq/pull/18745
@millerdev / @calellowitz
=> Better standardize "core" JavaScript inclusions

static/prelogin/js/section_appear.js
=> Run eslint --fix

ab_tests.py, templatetags/pricing_tags.py, urls.py, views.py
=> python-modernize corehq/apps/prelogin/ -w --future-unicode

templates/prelogin/_sections/pricing/lead.html, templates/prelogin/_sections/software_services/shared_pricing_table.html
Should go into production with https://github.com/dimagi/commcare-hq/pull/19833
=> update Standard pricing to 250
